### ISSUE TITLE
Trying to parse an array property as an object

### ISSUE THREAD

**Issue by fpietka** [brettminnie/breakfast-serializer#26]
I got the following error:
```
Warning: get_class() expects parameter 1 to be object, string given in vendor/brettminnie/breakfast-serializer/src/BreakfastSerializer/Serializer.php on line 78
```
Happens there:
https://github.com/brettminnie/breakfast-serializer/blob/feature/17_documentation/src/BreakfastSerializer/Serializer.php#L78

In my case, it happens when iterating through `BDBStudios\BreakfastSerializer::iterateClassProperties()` here:
https://github.com/brettminnie/breakfast-serializer/blob/feature/17_documentation/src/BreakfastSerializer/JSONSerializer.php#L216

Since my property is an array (with one entry in it, not sure it matters), it got caught and sent to `BDBStudios\BreakfastSerializer::objectToArray()`

I am not sure why `is_array()` leads to send it to this method.

**Comment by brettminnie** [comment]
Thanks @fpietka I'll write a test to replicate it then fix it accordingly

**Comment by brettminnie** [comment]
@fpietka can you provide me with a class example please, the following test class did not trigger the warning

```php
class ComplexClass extends SimpleClass
{
    /**
     * @var array
     */
    protected $dataStore;

    public function __construct()
    {
        parent::__construct();

        $this->name = 'Complex Class Instance';

        $this->dataStore = array(
            'foo',
            1,
            'dateInfo'  => new \DateTime(),
            'classInfo' => new SimpleClass()
        );
    }
}

```

**Comment by fpietka** [comment]
Fixed

**Comment by brettminnie** [comment]
Merci.  I'll rebase the document branch against develop in the morning
